In [5]:
import os
import re
import io
import requests
import zipfile
import pandas as pd
import numpy as np

In [6]:
company_df = pd.read_csv("../data/sp500_companies.csv")

company_df

,ticker,company_name,sector,subsector,cik
0,MMM,3M,Industrials,Industrial Conglomerates,66740
1,AOS,A. O. Smith,Industrials,Building Products,91142
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,1800
3,ABBV,AbbVie,Health Care,Biotechnology,1551152
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,1467373
...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,1524472
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,1041061
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,877212
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,1136869
502,ZTS,Zoetis,Health Care,Pharmaceuticals,1555280

In [41]:
def download_gdelt_gkg(timestamp):
    """
    timestamp format: YYYYMMDDHHMMSS (e.g. '20220103000000')
    """
    url = f"http://data.gdeltproject.org/gdeltv2/{timestamp}.gkg.csv.zip"
    try:
        r = requests.get(url, timeout=20)
        if r.status_code != 200:
            return None
        
        z = zipfile.ZipFile(io.BytesIO(r.content))
        df = pd.read_csv(
            z.open(z.namelist()[0]),
            sep="\t",
            header=None,
            low_memory=False,
            dtype=str,
            encoding="latin-1"   # IMPORTANT FIX
        )
        return df
    
    except Exception as e:
        print("Download error:", e)
        return None

def clean_url_to_text(url):
    if not isinstance(url, str):
        return ""
    url = url.replace("https://", "").replace("http://", "")
    url = re.sub(r'^[^/]+/', '', url)         # remove domain
    url = re.sub(r'[-_/]', ' ', url)         # replace -, _, / with spaces
    url = re.sub(r'[^a-zA-Z0-9 ]+', ' ', url)
    url = re.sub(r'\s+', ' ', url)
    return url.strip().lower()


def clean_snippet(text):
    if not isinstance(text, str):
        return ""
    text = re.sub(r'\d+', ' ', text)
    text = re.sub(r'[^a-zA-Z ]+', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip().lower()

def filter_company_news(gkg_df, company_df, date_str):
    results = []
    if gkg_df is None:
        return results

    # GDELT column references based on your file:
    name_list = gkg_df[1].astype(str).str.lower()
    url_main = gkg_df[4].astype(str).str.lower()
    url_alt  = gkg_df[26].astype(str).str.lower()
    snippet  = gkg_df[24].astype(str).str.lower()

    for _, c in company_df.iterrows():
        ticker = c['ticker']
        company = str(c['company_name']).lower()
        key = company.split()[0]     # first word of company name

        mask = (
            name_list.str.contains(key, na=False) |
            url_main.str.contains(key, na=False) |
            url_alt.str.contains(key, na=False) |
            snippet.str.contains(key, na=False)
        )

        matched = gkg_df[mask]

        for _, row in matched.iterrows():
            results.append({
                'date': date_str,
                'ticker': ticker,
                'url': row[4],           # MAIN URL
                'alt_url': row[26],      # alt URL
                'snippet': row[24],      # snippet field
                'headline': row[4]       # treat URL as headline base
            })

    return results

In [42]:
test_tickers = ["AAPL", "MSFT", "AMZN"]
test_company_df = company_df[company_df['ticker'].isin(test_tickers)]
test_company_df

,ticker,company_name,sector,subsector,cik
22,AMZN,Amazon,Consumer Discretionary,Broadline Retail,1018724
38,AAPL,Apple Inc.,Information Technology,"Technology Hardware, Storage & Peripherals",320193
316,MSFT,Microsoft,Information Technology,Systems Software,789019

In [43]:
test_date = "2022-01-03"
timestamp = test_date.replace("-", "") + "000000"

gkg = download_gdelt_gkg(timestamp)
rows = filter_company_news(gkg, test_company_df, test_date.replace("-", ""))
rows[:5], len(rows)

([{'date': '20220103',
   'ticker': 'AMZN',
   'url': 'https://www.cityandstateny.com/politics/2022/01/police-officer-mayors-first-day-job/360258/',
   'alt_url': "<PAGE_LINKS>https://compstat.nypdonline.org/2e5c3f4b-85c1-4635-83c6-22b27fe7c75c/view/89;https://en.wikipedia.org/wiki/Kosciuszko_Street_station;https://gothamist.com/news/eric-adams-sworn-110th-new-york-city-mayor;https://nypost.com/2021/12/30/nyc-social-services-provider-blew-city-money-on-staff-booze-cruise-fast-food-audit/;https://nypost.com/2022/01/01/eric-adams-makes-911-call-on-first-day-as/;https://nypost.com/2022/01/01/nyc-recorded-485-murders-in-2021/;https://twitter.com/MylesMill/status/1477264288964296707;https://twitter.com/NYPDnews/status/1477345880080482304;https://twitter.com/courtneycgross/status/1477263721445699586;https://twitter.com/courtneycgross/status/1477264329162506240;https://twitter.com/courtneycgross/status/1477268541044838403;https://twitter.com/courtneycgross/status/1477268987889303552;https://twitter.com/juliakmarsh/status/1477263755075592194;https://twitter.com/katie_honan/status/1477278426021220356;https://www.cityandstateny.com/opinion/2019/03/why-the-mayor-gives-the-nypd-a-free-ride/177598/;https://www.cityandstateny.com/policy/2020/03/how-new-yorks-programs-and-policies-are-keeping-the-homeless-on-the-street/176302/;https://www.cityandstateny.com/policy/2021/12/eric-adams-covid-19-plan-keeps-private-sector-vaccine-mandate-place/360248/;https://www.cityandstateny.com/politics/2020/02/who-can-actually-get-a-gun-in-new-york-city/176419/;https://www.cityandstateny.com/politics/2021/06/mtv-cribs-eric-adams-edition/182790/;https://www.cityandstateny.com/politics/2021/10/amazon-workers-file-union-election-new-york/186358/;https://www.cityandstateny.com/politics/2021/12/whos-who-eric-adams-administration/360056/;https://www.npr.org/2021/09/27/1040904770/fbi-data-murder-increase-2020;https://www.nytimes.com/2014/12/05/opinion/we-must-stop-police-abuse-of-black-men.html</PAGE_LINKS><PAGE_PRECISEPUBTIMESTAMP>20220102021300</PAGE_PRECISEPUBTIMESTAMP><PAGE_TITLE>Police officer mayor's first day on the job - City & State New York</PAGE_TITLE>",
   'snippet': '2,large,2444;33,staff members joined on,4145;9000000,dreams,4373;500,murders was the highest,5053;857,shooting victims reported,5167;3,questions,6576;',
   'headline': 'https://www.cityandstateny.com/politics/2022/01/police-officer-mayors-first-day-job/360258/'},
  {'date': '20220103',
   'ticker': 'AMZN',
   'url': 'https://listverse.com/2015/06/13/10-successful-people-trapped-in-their-parents-shadow/',
   'alt_url': "<PAGE_LINKS>http://articles.latimes.com/1987-12-29/news/mn-31830_1_anthony-west;http://dawdlez.com/;http://www-history.mcs.st-and.ac.uk/Biographies/Darwin.html;http://www.allmusic.com/artist/franz-xaver-wolfgang-mozart-mn0001676655/biography;http://www.asce.org/templates/publications-book-detail.aspx?id=6978;http://www.classiccat.net/mozart_fx/biography.php;http://www.classicfm.com/composers/mozart/news/mozart-son-franz-xaver-gravestone-vandalised/;http://www.einstein-website.de/biographies/einsteinhansalbert_content.html;http://www.famousscientists.org/aage-bohr/;http://www.geni.com/family-tree/index/6000000010799521427;http://www.lib.uiowa.edu/scua/msc/tomsc900/msc900/msc0900hanseinsteinpapers.html;http://www.nytimes.com/books/00/09/10/specials/west-newlife.html;http://www.theodore-roosevelt.com/tedjr.html;http://www.utahbeachnormandy.com/general-roosevelt.htm;http://www2.webster.edu/~woolflm/annafreud.html;https://books.google.ro/books?id=ZKIxAQAAIAAJ&dq=Employed+against+the+Mongol+invaders+of+Europe%2C+knightly+warfare+failed+even+more+disastrously+for+the+Poles+at+Legnica+and+the+Hungarians+at+Mohi+in+1241.+Feudal+Europe+was+saved+from+sharing+the+fate+of+China+and+Muscovy+not+by+its&focus=searchwithinvolume&q=unexpected+death;https://listverse.com/lvauthor/Jamie;https://twitter.com/raduxander;https://web.archive.org/web/20080609124833/http://royalsociety.org/downloaddoc.asp?id=4274;https://www.amazon.com/Heritage-Anthony-West/dp/1451605986;https://www.boundless.com/world-history/textbooks/boundless-world-history-i-ancient-1600-textbook/the-mongol-empire-13/the-mongol-empire-after-genghis-khan-1227-ce-1368-ce-62/the-mongol-empire-under-ogedei-conquest-of-eastern-europe-233-13330/;https://www.britannica.com/EBchecked/topic/151966/Sir-George-Darwin;https://www.gwu.edu/~erpapers/teachinger/glossary/smith-al.cfm;https://www.independent.co.uk/life-style/gadgets-and-tech/news/anna-freuds-119th-birthday-google-doodle-celebrates-the-life-of-revolutionary-child-psychoanalyst-and-daughter-of-sigmund-freud-9899329.html;https://www.nobelprize.org/nobel_prizes/physics/laureates/1975/bohr-bio.html;https://www.sdsc.edu/ScienceWomen/lovelace.html;https://www.theguardian.com/lifeandstyle/2010/nov/13/huxley-great-dynasties-aldous;https://www.theguardian.com/technology/2012/dec/10/ada-lovelace-honoured-google-doodle;https://www.theguardian.com/technology/2014/dec/03/anna-freud-google-doodle-child-psychoanalysis</PAGE_LINKS><PAGE_PRECISEPUBTIMESTAMP>20201120204900</PAGE_PRECISEPUBTIMESTAMP><PAGE_TITLE>10 Successful People Trapped In Their Parents' Shadow</PAGE_TITLE>",
   'snippet': '10,children,602;7,of whom survived into,616;3,of Darwin children,753;6,children with his wife,3096;2,formed a formidable physics,3728;6,children,5188;6,children together,7379;2,of them survived infancy,7403;3,sisters,7682;6,months old,7929;3,children,8730;2,highly successful parents,9785;2,famous parents,10461;8,children,11451;6,children,11865;',
   'headline': 'https://listverse.com/2015/06/13/10-successful-people-trapped-in-their-parents-shadow/'},
  {'date': '20220103',
   'ticker': 'AAPL',
   'url': 'https://www.nbcdfw.com/news/politics/twitter-permanently-suspends-marjorie-taylor-greenes-personal-account/2850137/',
   'alt_url': "<PAGE_LINKS>https://apps.apple.com/app/id331805052;https://play.google.com/store/apps/details</PAGE_LINKS><PAGE_PRECISEPUBTIMESTAMP>20220102111100</PAGE_PRECISEPUBTIMESTAMP><PAGE_ALTURL_AMP>https://www.nbcdfw.com/news/politics/twitter-permanently-suspends-marjorie-taylor-greenes-personal-account/2850137/?amp</PAGE_ALTURL_AMP><PAGE_TITLE>Twitter Permanently Suspends Marjorie Taylor Greene's Personal Account &#x2013; NBC 5 Dallas-Fort Worth</PAGE_TITLE>",
   'snippet': '3,strikes earn a 12-hour,493;2,committee assignments,1730;1000000,of accounts worldwide,2098;',
   'headline': 'https://www.nbcdfw.com/news/politics/twitter-permanently-suspends-marjorie-taylor-greenes-personal-account/2850137/'},
  {'date': '20220103',
   'ticker': 'AAPL',
   'url': 'https://www.nbcdfw.com/news/business/money-report/stock-futures-rise-ahead-of-first-trading-day-of-2022/2850254/',
   'alt_url': '<PAGE_LINKS>https://apps.apple.com/app/id331805052;https://play.google.com/store/apps/details;https://www.cnbc.com/2021/12/30/stock-market-futures-open-to-close-news.html;https://www.cnbc.com/2022/01/01/amid-another-covid-surge-schools-and-businesses-find-plans-disrupted-.html;https://www.cnbc.com/2022/01/01/severe-weather-omicron-infections-drive-thousands-more-us-flight-cancellations.html;https://www.cnbc.com/2022/01/02/goldman-sachs-asks-us-employees-to-work-from-home-until-jan-18.html;https://www.cnbc.com/2022/01/02/us-is-considering-recommending-that-individuals-exposed-to-covid-end-isolation-if-theyve-tested-negative-for-the-virus-after-five-days-dr-fauci-says.html;https://www.cnbc.com/quotes/TSLA&__source=OTS%7Cfinance%7Cinline%7Cstory%7C&par=OTS&doc=106995632</PAGE_LINKS><PAGE_PRECISEPUBTIMESTAMP>20220102170100</PAGE_PRECISEPUBTIMESTAMP><PAGE_ALTURL_AMP>https://www.nbcdfw.com/news/business/money-report/stock-futures-rise-ahead-of-first-trading-day-of-2022/2850254/?amp</PAGE_ALTURL_AMP><PAGE_TITLE>Stock Futures Rise Ahead of First Trading Day of 2022</PAGE_TITLE>',
   'snippet': '80,points,129;500,added 0 3%,152;100,futures gained 0 4%,175;500,rose nearly 27% for,347;600,deliveries,1683;4,quarter,1704;',
   'headline': 'https://www.nbcdfw.com/news/business/money-report/stock-futures-rise-ahead-of-first-trading-day-of-2022/2850254/'},
  {'date': '20220103',
   'ticker': 'AAPL',
   'url': 'https://appleinsider.com/articles/22/01/02/the-best-iphone-widget-apps-for-customizing-your-iphone-home-screen',
   'alt_url': '<PAGE_LINKS>https://appleinsider.com/inside/ios;https://appleinsider.com/inside/ios-14;https://appleinsider.com/inside/ios-15;https://appleinsider.com/inside/iphone;https://apps.apple.com/us/app/bears-countdown/id1536711520;https://apps.apple.com/us/app/id1524227906;https://apps.apple.com/us/app/launcher-notification-center/id905099592;https://apps.apple.com/us/app/smart-battery-widget/id1514578375;https://apps.apple.com/us/app/widgetsmith/id1523682319</PAGE_LINKS><PAGE_ALTURL_AMP>https://appleinsider.com/articles/22/01/02/the-best-iphone-widget-apps-for-customizing-your-iphone-home-screen/amp/</PAGE_ALTURL_AMP><PAGE_TITLE>The best iPhone widget apps for customizing your iPhone home screen</PAGE_TITLE>',
   'snippet': '35,health,3724;',
   'headline': 'https://appleinsider.com/articles/22/01/02/the-best-iphone-widget-apps-for-customizing-your-iphone-home-screen'}],
 12)

In [11]:
news_raw = pd.DataFrame(rows)
news_raw.head()

,date,ticker,url,alt_url,snippet,headline
0,20220103,AMZN,https://www.cityandstateny.com/politics/2022/0...,<PAGE_LINKS>https://compstat.nypdonline.org/2e...,"2,large,2444;33,staff members joined on,4145;9...",https://www.cityandstateny.com/politics/2022/0...
1,20220103,AMZN,https://listverse.com/2015/06/13/10-successful...,<PAGE_LINKS>http://articles.latimes.com/1987-1...,"10,children,602;7,of whom survived into,616;3,...",https://listverse.com/2015/06/13/10-successful...
2,20220103,AAPL,https://www.nbcdfw.com/news/politics/twitter-p...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"3,strikes earn a 12-hour,493;2,committee assig...",https://www.nbcdfw.com/news/politics/twitter-p...
3,20220103,AAPL,https://www.nbcdfw.com/news/business/money-rep...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"80,points,129;500,added 0 3%,152;100,futures g...",https://www.nbcdfw.com/news/business/money-rep...
4,20220103,AAPL,https://appleinsider.com/articles/22/01/02/the...,<PAGE_LINKS>https://appleinsider.com/inside/io...,"35,health,3724;",https://appleinsider.com/articles/22/01/02/the...

In [12]:
news_raw['headline_text'] = news_raw['url'].apply(clean_url_to_text)
news_raw['snippet_text'] = news_raw['snippet'].apply(clean_snippet)

# Combined text for FinBERT
news_raw['combined_text'] = (
    news_raw['headline_text'] + " " + news_raw['snippet_text']
).str.strip()

news_raw.head()

,date,ticker,url,alt_url,snippet,headline,headline_text,snippet_text,combined_text
0,20220103,AMZN,https://www.cityandstateny.com/politics/2022/0...,<PAGE_LINKS>https://compstat.nypdonline.org/2e...,"2,large,2444;33,staff members joined on,4145;9...",https://www.cityandstateny.com/politics/2022/0...,politics 2022 01 police officer mayors first d...,large staff members joined on dreams murders w...,politics 2022 01 police officer mayors first d...
1,20220103,AMZN,https://listverse.com/2015/06/13/10-successful...,<PAGE_LINKS>http://articles.latimes.com/1987-1...,"10,children,602;7,of whom survived into,616;3,...",https://listverse.com/2015/06/13/10-successful...,2015 06 13 10 successful people trapped in the...,children of whom survived into of darwin child...,2015 06 13 10 successful people trapped in the...
2,20220103,AAPL,https://www.nbcdfw.com/news/politics/twitter-p...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"3,strikes earn a 12-hour,493;2,committee assig...",https://www.nbcdfw.com/news/politics/twitter-p...,news politics twitter permanently suspends mar...,strikes earn a hour committee assignments of a...,news politics twitter permanently suspends mar...
3,20220103,AAPL,https://www.nbcdfw.com/news/business/money-rep...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"80,points,129;500,added 0 3%,152;100,futures g...",https://www.nbcdfw.com/news/business/money-rep...,news business money report stock futures rise ...,points added futures gained rose nearly for de...,news business money report stock futures rise ...
4,20220103,AAPL,https://appleinsider.com/articles/22/01/02/the...,<PAGE_LINKS>https://appleinsider.com/inside/io...,"35,health,3724;",https://appleinsider.com/articles/22/01/02/the...,articles 22 01 02 the best iphone widget apps ...,health,articles 22 01 02 the best iphone widget apps ...

In [13]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Running on:", device)

tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert").to(device)
model.eval()

/home/zeyuzh/.conda/envs/jupyter_env/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Running on: cuda

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=3, bias=True)
)

In [14]:
def finbert_gpu(texts, batch_size=32):
    all_probs = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        enc = tokenizer(batch, padding=True, truncation=True, max_length=128, return_tensors="pt").to(device)
        
        with torch.no_grad():
            logits = model(**enc).logits
        
        probs = torch.softmax(logits, dim=1).cpu().numpy()
        all_probs.append(probs)

    return np.vstack(all_probs)

In [15]:
probs = finbert_gpu(news_raw['combined_text'].tolist())
news_raw['neg'] = probs[:,0]
news_raw['neu'] = probs[:,1]
news_raw['pos'] = probs[:,2]

In [16]:
news_raw.head()

,date,ticker,url,alt_url,snippet,headline,headline_text,snippet_text,combined_text,neg,neu,pos
0,20220103,AMZN,https://www.cityandstateny.com/politics/2022/0...,<PAGE_LINKS>https://compstat.nypdonline.org/2e...,"2,large,2444;33,staff members joined on,4145;9...",https://www.cityandstateny.com/politics/2022/0...,politics 2022 01 police officer mayors first d...,large staff members joined on dreams murders w...,politics 2022 01 police officer mayors first d...,0.146713,0.254010,0.599277
1,20220103,AMZN,https://listverse.com/2015/06/13/10-successful...,<PAGE_LINKS>http://articles.latimes.com/1987-1...,"10,children,602;7,of whom survived into,616;3,...",https://listverse.com/2015/06/13/10-successful...,2015 06 13 10 successful people trapped in the...,children of whom survived into of darwin child...,2015 06 13 10 successful people trapped in the...,0.043823,0.086343,0.869834
2,20220103,AAPL,https://www.nbcdfw.com/news/politics/twitter-p...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"3,strikes earn a 12-hour,493;2,committee assig...",https://www.nbcdfw.com/news/politics/twitter-p...,news politics twitter permanently suspends mar...,strikes earn a hour committee assignments of a...,news politics twitter permanently suspends mar...,0.011281,0.880396,0.108323
3,20220103,AAPL,https://www.nbcdfw.com/news/business/money-rep...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"80,points,129;500,added 0 3%,152;100,futures g...",https://www.nbcdfw.com/news/business/money-rep...,news business money report stock futures rise ...,points added futures gained rose nearly for de...,news business money report stock futures rise ...,0.787802,0.103075,0.109123
4,20220103,AAPL,https://appleinsider.com/articles/22/01/02/the...,<PAGE_LINKS>https://appleinsider.com/inside/io...,"35,health,3724;",https://appleinsider.com/articles/22/01/02/the...,articles 22 01 02 the best iphone widget apps ...,health,articles 22 01 02 the best iphone widget apps ...,0.113584,0.012578,0.873838

In [17]:
daily_news = (
    news_raw.groupby(['date','ticker'])
    .agg(
        sent_mean=('pos', 'mean'),
        sent_vol=('pos', 'std'),
        pos_ratio=('pos', lambda x: (x > 0.5).mean()),
        neg_ratio=('neg', lambda x: (x > 0.5).mean()),
        neu_ratio=('neu', lambda x: (x > 0.5).mean()),
        news_count=('combined_text', 'count')
    )
    .fillna(0)
    .reset_index()
)

daily_news

,date,ticker,sent_mean,sent_vol,pos_ratio,neg_ratio,neu_ratio,news_count
0,20220103,AAPL,0.627835,0.345108,0.75,0.125,0.125,8
1,20220103,AMZN,0.734556,0.191313,1.00,0.000,0.000,2
2,20220103,MSFT,0.524660,0.561535,0.50,0.000,0.500,2

In [18]:
date_str = "20220103"
daily_rows = []

for hour in range(24):
    ts = f"{date_str}{hour:02d}0000"
    gkg = download_gdelt_gkg(ts)
    if gkg is not None:
        rows = filter_company_news(gkg, test_company_df, date_str)
        daily_rows.extend(rows)

news_raw = pd.DataFrame(daily_rows)

In [19]:
news_raw

,date,ticker,url,alt_url,snippet,headline
0,20220103,AMZN,https://www.cityandstateny.com/politics/2022/0...,<PAGE_LINKS>https://compstat.nypdonline.org/2e...,"2,large,2444;33,staff members joined on,4145;9...",https://www.cityandstateny.com/politics/2022/0...
1,20220103,AMZN,https://listverse.com/2015/06/13/10-successful...,<PAGE_LINKS>http://articles.latimes.com/1987-1...,"10,children,602;7,of whom survived into,616;3,...",https://listverse.com/2015/06/13/10-successful...
2,20220103,AAPL,https://www.nbcdfw.com/news/politics/twitter-p...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"3,strikes earn a 12-hour,493;2,committee assig...",https://www.nbcdfw.com/news/politics/twitter-p...
3,20220103,AAPL,https://www.nbcdfw.com/news/business/money-rep...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"80,points,129;500,added 0 3%,152;100,futures g...",https://www.nbcdfw.com/news/business/money-rep...
4,20220103,AAPL,https://appleinsider.com/articles/22/01/02/the...,<PAGE_LINKS>https://appleinsider.com/inside/io...,"35,health,3724;",https://appleinsider.com/articles/22/01/02/the...
...,...,...,...,...,...,...
525,20220103,AAPL,https://www.kmaj.com/2021/06/15/this-months-cr...,<PAGE_LINKS>https://www.kmaj.com/2019/01/09/cr...,"1,Math teacher at Rossville,336;1,dollars ,977...",https://www.kmaj.com/2021/06/15/this-months-cr...
526,20220103,AAPL,https://www.nytimes.com/2022/01/03/briefing/om...,<PAGE_LINKS>http://www.nytimes.com/newsletters...,"3000000000000,dollars company,1170;10000000000...",https://www.nytimes.com/2022/01/03/briefing/om...
527,20220103,AAPL,https://www.gizchina.com/2022/01/03/iphone-14-...,<PAGE_LINKS>http://www.apple.com;https://www.g...,"14,series,59;14,series will come with,253;14,s...",https://www.gizchina.com/2022/01/03/iphone-14-...
528,20220103,AAPL,https://ricochet.com/podcast/sara-carter-podca...,<PAGE_LINKS>https://itunes.apple.com/us/podcas...,NaN,https://ricochet.com/podcast/sara-carter-podca...
529,20220103,MSFT,https://industrialit.com.au/malaysia-artificia...,<PAGE_LINKS>https://industrialit.com.au/cdn-cg...,"8,analysts working days,3183;100,Global Fortun...",https://industrialit.com.au/malaysia-artificia...

In [22]:
all_rows = []

test_tickers = ["AAPL", "MSFT", "AMZN"]

test_start = "2022-01-03"
test_end   = "2022-01-10"
test_dates = pd.date_range(test_start, test_end, freq="D")
for d in test_dates:
    date_str = d.strftime("%Y%m%d")
    for hour in range(24):
        ts = f"{date_str}{hour:02d}0000"
        gkg = download_gdelt_gkg(ts)
        if gkg is not None:
            rows = filter_company_news(gkg, test_company_df, date_str)
            all_rows.extend(rows)

news_raw = pd.DataFrame(all_rows)

In [23]:
news_raw

,date,ticker,url,alt_url,snippet,headline
0,20220103,AMZN,https://www.cityandstateny.com/politics/2022/0...,<PAGE_LINKS>https://compstat.nypdonline.org/2e...,"2,large,2444;33,staff members joined on,4145;9...",https://www.cityandstateny.com/politics/2022/0...
1,20220103,AMZN,https://listverse.com/2015/06/13/10-successful...,<PAGE_LINKS>http://articles.latimes.com/1987-1...,"10,children,602;7,of whom survived into,616;3,...",https://listverse.com/2015/06/13/10-successful...
2,20220103,AAPL,https://www.nbcdfw.com/news/politics/twitter-p...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"3,strikes earn a 12-hour,493;2,committee assig...",https://www.nbcdfw.com/news/politics/twitter-p...
3,20220103,AAPL,https://www.nbcdfw.com/news/business/money-rep...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"80,points,129;500,added 0 3%,152;100,futures g...",https://www.nbcdfw.com/news/business/money-rep...
4,20220103,AAPL,https://appleinsider.com/articles/22/01/02/the...,<PAGE_LINKS>https://appleinsider.com/inside/io...,"35,health,3724;",https://appleinsider.com/articles/22/01/02/the...
...,...,...,...,...,...,...
4609,20220110,MSFT,https://www.windowscentral.com/forza-street-cl...,<PAGE_LINKS>https://support.forzamotorsport.ne...,"5,is now available,1906;5,is available through...",https://www.windowscentral.com/forza-street-cl...
4610,20220110,MSFT,http://www.consumerelectronicsnet.com/f5-adds-...,<PAGE_LINKS>https://twitter.com/F5&esheet=5256...,"11,members,1799;10,of whom,1809;3,directors wh...",http://www.consumerelectronicsnet.com/f5-adds-...
4611,20220110,MSFT,https://www.windowscentral.com/phil-spencer-xb...,<PAGE_LINKS>https://www.nytimes.com/2022/01/10...,NaN,https://www.windowscentral.com/phil-spencer-xb...
4612,20220110,MSFT,https://www.esecurityplanet.com/threats/creden...,<PAGE_LINKS>https://ag.ny.gov/press-release/20...,"1000000,online accounts at 17,361;17,companies...",https://www.esecurityplanet.com/threats/creden...
4613,20220110,MSFT,https://forums.appleinsider.com/discussion/225744,<PAGE_LINKS>https://forums.appleinsider.com/pr...,"5,posts,513;",https://forums.appleinsider.com/discussion/225744

In [24]:
news_raw['headline_text'] = news_raw['url'].apply(clean_url_to_text)
news_raw['snippet_text']  = news_raw['snippet'].apply(clean_snippet)
news_raw['combined_text'] = news_raw['headline_text'] + " " + news_raw['snippet_text']
news_raw.head()

,date,ticker,url,alt_url,snippet,headline,headline_text,snippet_text,combined_text
0,20220103,AMZN,https://www.cityandstateny.com/politics/2022/0...,<PAGE_LINKS>https://compstat.nypdonline.org/2e...,"2,large,2444;33,staff members joined on,4145;9...",https://www.cityandstateny.com/politics/2022/0...,politics 2022 01 police officer mayors first d...,large staff members joined on dreams murders w...,politics 2022 01 police officer mayors first d...
1,20220103,AMZN,https://listverse.com/2015/06/13/10-successful...,<PAGE_LINKS>http://articles.latimes.com/1987-1...,"10,children,602;7,of whom survived into,616;3,...",https://listverse.com/2015/06/13/10-successful...,2015 06 13 10 successful people trapped in the...,children of whom survived into of darwin child...,2015 06 13 10 successful people trapped in the...
2,20220103,AAPL,https://www.nbcdfw.com/news/politics/twitter-p...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"3,strikes earn a 12-hour,493;2,committee assig...",https://www.nbcdfw.com/news/politics/twitter-p...,news politics twitter permanently suspends mar...,strikes earn a hour committee assignments of a...,news politics twitter permanently suspends mar...
3,20220103,AAPL,https://www.nbcdfw.com/news/business/money-rep...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"80,points,129;500,added 0 3%,152;100,futures g...",https://www.nbcdfw.com/news/business/money-rep...,news business money report stock futures rise ...,points added futures gained rose nearly for de...,news business money report stock futures rise ...
4,20220103,AAPL,https://appleinsider.com/articles/22/01/02/the...,<PAGE_LINKS>https://appleinsider.com/inside/io...,"35,health,3724;",https://appleinsider.com/articles/22/01/02/the...,articles 22 01 02 the best iphone widget apps ...,health,articles 22 01 02 the best iphone widget apps ...

In [25]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Running on:", device)

tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert").to(device)
model.eval()

Running on: cuda

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=3, bias=True)
)

In [26]:
def finbert_gpu(texts, batch_size=32):
    all_probs = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        
        enc = tokenizer(
            batch,
            padding=True,
            truncation=True,
            max_length=128,
            return_tensors="pt"
        ).to(device)

        with torch.no_grad():
            logits = model(**enc).logits
        
        probs = torch.softmax(logits, dim=1).cpu().numpy()
        all_probs.append(probs)
    
    return np.vstack(all_probs)

In [27]:
probs = finbert_gpu(news_raw['combined_text'].tolist())

news_raw['neg'] = probs[:,0]
news_raw['neu'] = probs[:,1]
news_raw['pos'] = probs[:,2]

news_raw.head()

,date,ticker,url,alt_url,snippet,headline,headline_text,snippet_text,combined_text,neg,neu,pos
0,20220103,AMZN,https://www.cityandstateny.com/politics/2022/0...,<PAGE_LINKS>https://compstat.nypdonline.org/2e...,"2,large,2444;33,staff members joined on,4145;9...",https://www.cityandstateny.com/politics/2022/0...,politics 2022 01 police officer mayors first d...,large staff members joined on dreams murders w...,politics 2022 01 police officer mayors first d...,0.146713,0.254009,0.599277
1,20220103,AMZN,https://listverse.com/2015/06/13/10-successful...,<PAGE_LINKS>http://articles.latimes.com/1987-1...,"10,children,602;7,of whom survived into,616;3,...",https://listverse.com/2015/06/13/10-successful...,2015 06 13 10 successful people trapped in the...,children of whom survived into of darwin child...,2015 06 13 10 successful people trapped in the...,0.043823,0.086343,0.869834
2,20220103,AAPL,https://www.nbcdfw.com/news/politics/twitter-p...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"3,strikes earn a 12-hour,493;2,committee assig...",https://www.nbcdfw.com/news/politics/twitter-p...,news politics twitter permanently suspends mar...,strikes earn a hour committee assignments of a...,news politics twitter permanently suspends mar...,0.011281,0.880396,0.108323
3,20220103,AAPL,https://www.nbcdfw.com/news/business/money-rep...,<PAGE_LINKS>https://apps.apple.com/app/id33180...,"80,points,129;500,added 0 3%,152;100,futures g...",https://www.nbcdfw.com/news/business/money-rep...,news business money report stock futures rise ...,points added futures gained rose nearly for de...,news business money report stock futures rise ...,0.787802,0.103075,0.109123
4,20220103,AAPL,https://appleinsider.com/articles/22/01/02/the...,<PAGE_LINKS>https://appleinsider.com/inside/io...,"35,health,3724;",https://appleinsider.com/articles/22/01/02/the...,articles 22 01 02 the best iphone widget apps ...,health,articles 22 01 02 the best iphone widget apps ...,0.113584,0.012578,0.873838

In [28]:
daily_news = (
    news_raw.groupby(['date','ticker'])
    .agg(
        sent_mean=('pos', 'mean'),
        sent_vol=('pos', 'std'),
        pos_ratio=('pos', lambda x: (x > 0.5).mean()),
        neg_ratio=('neg', lambda x: (x > 0.5).mean()),
        neu_ratio=('neu', lambda x: (x > 0.5).mean()),
        news_count=('combined_text', 'count')
    )
    .fillna(0)
    .reset_index()
)

daily_news

,date,ticker,sent_mean,sent_vol,pos_ratio,neg_ratio,neu_ratio,news_count
0,20220103,AAPL,0.650454,0.330671,0.726115,0.098726,0.162420,314
1,20220103,AMZN,0.807229,0.202903,0.901734,0.023121,0.069364,173
2,20220103,MSFT,0.757459,0.246255,0.860465,0.046512,0.093023,43
3,20220104,AAPL,0.595235,0.321596,0.621469,0.135593,0.216573,531
4,20220104,AMZN,0.769795,0.252340,0.863454,0.008032,0.120482,249
5,20220104,MSFT,0.659336,0.342644,0.704545,0.227273,0.045455,44
6,20220105,AAPL,0.659324,0.296977,0.721839,0.034483,0.216092,435
7,20220105,AMZN,0.772545,0.255051,0.861702,0.024823,0.106383,282
8,20220105,MSFT,0.766895,0.222253,0.868852,0.049180,0.081967,61
9,20220106,AAPL,0.673179,0.312200,0.724796,0.043597,0.201635,367
10,20220106,AMZN,0.718880,0.283320,0.812500,0.041667,0.137500,240
11,20220106,MSFT,0.781443,0.271839,0.851064,0.106383,0.042553,47
12,20220107,AAPL,0.700456,0.282181,0.774347,0.042755,0.166271,421
13,20220107,AMZN,0.796173,0.227613,0.885572,0.034826,0.074627,201
14,20220107,MSFT,0.781630,0.233746,0.836735,0.020408,0.122449,49
15,20220108,AAPL,0.683252,0.286651,0.761682,0.051402,0.177570,214
16,20220108,AMZN,0.787329,0.214275,0.875000,0.000000,0.116667,120
17,20220108,MSFT,0.915949,0.024787,1.000000,0.000000,0.000000,12
18,20220109,AAPL,0.707597,0.283841,0.778523,0.020134,0.174497,149
19,20220109,AMZN,0.774127,0.262148,0.857143,0.000000,0.142857,70
20,20220109,MSFT,0.825787,0.229268,0.882353,0.117647,0.000000,17
21,20220110,AAPL,0.677108,0.310674,0.740506,0.028481,0.202532,316
22,20220110,AMZN,0.827456,0.193284,0.925234,0.009346,0.060748,214
23,20220110,MSFT,0.794677,0.256137,0.866667,0.022222,0.111111,45